version: '3.5'

services:
  frontend:
    image: kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: km-frontend
    volumes:
      - front:/src/app/fdata
  backend:
    image: kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - back:/src/model
    depends_on:
      - training
  training:
    image: kurkkumopo-training
    volumes:
      - back:/src/model
      - data:/src/data
      - imgs:/src/imgs

volumes:
  front:
  back:
  data:
  imgs:
